language: cpp
compiler: gcc

cache:
  pip: true

before_install:
  - pyenv install 3.6.0
  - pyenv local 3.6.0
  - pip install wheel

install:
  - mkdir build
  - cd build
  - cmake ..

script: mpipe_test
