dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

cache:
  pip: true
  directories:
  - /opt/pyenv

install:
  - pyenv install 3.6.0
  - pyenv local 3.6.0
  - pip install wheel

before_script:
  - export CC=gcc-6
  - export CXX=g++-6

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./mpipe_test
