language: cpp

compiler:
  - gcc
  - clang

cache:
  pip: true

before_install:
  - sudo apt-get update -q
  - sudo apt-get install python3 -y
  - pip install wheel

install:
  - mkdir build
  - cd build
  - cmake ..

script: mpipe_test
