dist: trusty
sudo: require
language: cpp
compiler: gcc

cache:
  pip: true
  directories:
  - /opt/pyenv

before_install:
  - pyenv install 3.6.0
  - pyenv local 3.6.0
  - pip install wheel

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: 
  - ./mpipe_test
